### ISSUE TITLE
Follow HTTP redirect when discovering servers

### ISSUE THREAD

**Issue by oczkoisse** [jellyfin/jellyfin-sdk-kotlin#769] opened 2023-06-25 19:13 UTC
I'm following up on an issue I described in https://github.com/jellyfin/jellyfin-android/issues/949#issuecomment-1606213544.  I've an HTTP redirect set from a custom domain to the Jellyfin server. Works great on browsers with both HTTP and HTTPS, even on LG webos app. The android client, however, refuses to follow the redirect URL and instead lists the tried candidates:

```
Tried 5 candidates for input, without success.

Unable to reach server:
- https://subdomain.domain.com
- https://subdomain.domain.com:8096
- https://subdomain.domain.com:8920
- http://subdomain.domain.com
- http://subdomain.domain.com:8096
```

Could it be possible to allow redirected URLs (301/302) to be acceptable as server URLs instead of outright rejecting them? I believe it could be fixed by adjusting the acceptable response code here: https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/master/jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt#L125.

**Comment by nielsvanvelzen** [comment] 2023-06-25 20:16
Quoting from a reply to a similar recent question:
> Our Android clients do not follow redirects for security reasons. We might add a special case for discovery (when you're adding the server) to save the redirected URL at some point.

We do have support for following redirects in the SDK but it's always disabled during discovery and our official apps always disable it. 

We should at the very least change the error message to say something like "ignored redirect for candidate X" and preferably follow the redirect while testing and if it redirects to a valid server show a pop-up to the user to confirm if the address redirected to is valid.

**Comment by nielsvanvelzen** [comment] 2023-10-09 19:35
Looking at the issues now I believe this is really a duplicate of #471 so I'll close this one.

**Closed by nielsvanvelzen** 2023-10-09 19:35 UTC
Labels: enhancement

**Comment by unwenliu** [comment] 2024-03-14 05:46
> I'm following up on an issue I described in [jellyfin/jellyfin-android#949 (comment)](https://github.com/jellyfin/jellyfin-android/issues/949#issuecomment-1606213544). I've an HTTP redirect set from a custom domain to the Jellyfin server. Works great on browsers with both HTTP and HTTPS, even on LG webos app. The android client, however, refuses to follow the redirect URL and instead lists the tried candidates:
> 
> ```
> Tried 5 candidates for input, without success.
> 
> Unable to reach server:
> - https://subdomain.domain.com
> - https://subdomain.domain.com:8096
> - https://subdomain.domain.com:8920
> - http://subdomain.domain.com
> - http://subdomain.domain.com:8096
> ```
> 
> Could it be possible to allow redirected URLs (301/302) to be acceptable as server URLs instead of outright rejecting them? I believe it could be fixed by adjusting the acceptable response code here: https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/master/jellyfin-core/src/commonMain/kotlin/org/jellyfin/sdk/discovery/RecommendedServerDiscovery.kt#L125.

I'm modified `followRedirects=true`，compile the sdk and publishToMavenLocal，
jellyfin-andriod project build apk with local sdk，it is not work，can u tell me how to do it
